### ISSUE TITLE
How to style the search bar and the map

### ISSUE THREAD

**Issue by ArdaMT** [jgravois/bootstrap-geocoder#2]
Hi John, 

this is my first message. I hope, im using the right github feature for our further discussion. I know about this link you've suggested in your e-mail: http://esri.github.io/esri-leaflet/examples/geocoding-control.html. actually this is a good alternative. but for my visual perception tests I wanted to have a search bar that is below the map. For that l found your code to be better because you are using a seperate textinput. I could style your text input and the map like I described above, with the map being right above the search bar. But, still there remains the problem that the search bar instantly removes  a text input once  the adress/location is chosen from the drop down menu. I would like to keep that input visible. Also I would like to place a marker on that given adress on the map.  im attaching my modified version of your index.html here, just in case. 

It's not optimal for my test purposes but i would also be down with using the alternative map in the link above. but in that case the search bar has to be placed at the bottom of the map and also it needs to be visible at all times and not only get activated with a click. 
Since it's a perception experiment that I am doing, my prof. is very specific about the visual requirements. That's why im trying to style the map and the search bar in a certain way.
Arda

[index.txt](https://github.com/jgravois/bootstrap-geocoder/files/3805720/index.txt)

**Comment by jgravois** [comment]
hi @ardamelih! I don't write code to order, but if all you're trying to do is customize the demo page for this repo to show the input _and_ the map, you should be able to accomplish that in a couple steps.

1. reorder the intro and map divs
https://github.com/jgravois/bootstrap-geocoder/blob/e4a1f0b45ff35f5512fd01dcba0fae51b7b78b86/index.html#L85-L86

2. update the `#map` .css so that its height is no longer 100% of the page
https://github.com/jgravois/bootstrap-geocoder/blob/e4a1f0b45ff35f5512fd01dcba0fae51b7b78b86/index.html#L39-L44

3. stop toggling block/none on the elements to show/hide them.
https://github.com/jgravois/bootstrap-geocoder/blob/e4a1f0b45ff35f5512fd01dcba0fae51b7b78b86/index.html#L114-L115

best of luck!

**Comment by ArdaMT** [comment]
Hi John, 

thx for the tips. i had already done all of that, when I embedded your code in my test.
Also wasn't expecting you to write code for me. sorry, if you got that impression! 
Like I mentioned above, my problem is the textinput getting removed from the input area . anyways, I guess I will look a bit more through your .js files to see if I can make some changes to achieve that and  to add a marker to the map.
thx again!

**Comment by jgravois** [comment]
sorry, I didn't give your first post a good read.

> I would like to place a marker on that given address on the map.

you can find an example of code that achieves that in the [demo I linked to previously](http://esri.github.io/esri-leaflet/examples/geocoding-control.html).

> my problem is the textinput getting removed from the input area

AFAIK that's the default (non-customizable) behavior of esri-leaflet-geocoder. you could get yourself into the weeds trying to edit that plugin's source code, but you'd be _far_ better off just taking advantage of the fact that the object returned by the [results](http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#results) event includes a reference to the text that was used in the search.

```js
searchControl.on('results', function (data) {
  console.log(data.text) 
  // >> 'Berlin, Germany'
  // StackOverflow should be able to help you display this string in a <div> of your own
);
```
this isn't currently documented so I proposed a change to fix that.

https://github.com/Esri/esri-leaflet-doc/pull/260

the way I figured it out was by opening up the browser developer tools, setting a breakpoint and inspecting it.

![Screen Shot 2019-11-04 at 12 21 09 PM](https://user-images.githubusercontent.com/3011734/68154973-9c103680-fefd-11e9-83b3-be4df0b309e1.png)

**Comment by ArdaMT** [comment]
Hey, thanks a lot. For now, I have  a dirty solution for the input using `document.getElementById('address').value=data.text `

**Comment by jgravois** [comment]
nothing wrong with that. good luck with your project!
