### ISSUE TITLE
How to get results as a list

### ISSUE THREAD

**Issue by DennisMuchiri** [jgravois/bootstrap-geocoder#4]
I am implementing a custom autocomplete with this...How can I get the location predictions as  a list not bound to an input element?

**Comment by jgravois** [comment]
> How can I get the location predictions as a list not bound to an input element?

instead of allowing the custom control to create a new `<ul>` internally, you'd need it to refer to one that already exists in the DOM. 

https://github.com/jgravois/bootstrap-geocoder/blob/master/src/GeosearchInput.js#L46-L51

```js
const list = document.querySelector('your-existing-list')
const suggestionItem = L.DomUtil.create('li', 'geocoder-control-suggestion', list);
```
