### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by igorchernenko92** [jgravois/bootstrap-geocoder#5]
Have a lot of issues while building
Could you please update the config files to have the ability to build the project ?
Really thanks in advance

**Comment by jgravois** [comment]
its tough for me to resolve the error you are having knowing so little about it.
what exactly are you seeing?

**Comment by igorchernenko92** [comment]
Here the details
https://drive.google.com/file/d/1YBva7GKOx4vm4ZAKQGl40AKIycxfT0nv/view?usp=sharing

**Comment by jgravois** [comment]
what version of rollup is installed?

**Comment by igorchernenko92** [comment]
0.25.8
https://drive.google.com/file/d/15aS05Jk-tA_JEId8s-LsqXgSEyHyrxKF/view?usp=sharing
Also i was trying it with the latest 2.3.2. Same result

**Comment by jgravois** [comment]
i updated some dependencies and made a few tweaks to the rollup config in #6 (and 💅 7e5cad8). 

i tried updating 'esri-leaflet-geocoder' too but ran into a snag and couldn't be bothered to debug it, so i reverted to pinning it.
 
hope that helps.
