### ISSUE TITLE
Pre-filled Input

### ISSUE THREAD

**Issue by sierracircle** [jgravois/bootstrap-geocoder#9]
Do you think it is possible to have the input field already have content and the map goes straight to that location rather than having to click on the input for search results?

**Comment by jgravois** [comment]
definitely.

**Comment by sierracircle** [comment]
I had someone help me put this together, here is the code based on your bootstrap-geocoder. I am using this in a Wordpress Website to provide a field for putting in an address when editing a post and storing that address on save (with a little map)...then displaying that address and map on the front-end.

The php variable   $business_location;  in this example will be pulled from the wp-database:

`   <div class="osm box">


      <input type="text" id="address-search" class="map_address" name="business_location"
        value="<?php echo $no_business_location; ?>"
        style="padding: 5px; font-size: 14px; width: 100%; margin: 5px 0px 20px 0px; " />
    </div>


    <div id="map">


      <script>
        
        var map = L.map('map').setView([45.5165, -122.6764], 3);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        var search = L.esri.BootstrapGeocoder.search({
          inputTag: 'address-search',
          placeholder: '<?php echo $business_location; ?>'
        }).addTo(map);

        //adding layer groups on the search control
        var results = L.layerGroup().addTo(map);

        search.on('results', function (data) {
          results.clearLayers();
          if (data && data.results[0]) {
            results.addLayer(L.marker(data.results[0].latlng));
            document.getElementById('address-search').value = data.results[0].properties.LongLabel
            map.setView(data.results[0].latlng)
          }else{
            map.setView([45.5165, -122.6764], 3)
          }
          
        })

        var txtbox = document.getElementById('address-search');

        var ev = new KeyboardEvent('keydown', {
          code: "Enter",
          key: "Enter",
          keyCode: 13,
          type: "keydown",
          which: 13
        });

        txtbox.dispatchEvent(ev);
       

        
      </script>

    </div>



  </div>
`
